CREATE SEQUENCE Customer_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Shipping_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Product_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Order_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
